import type {
  AuthType,
  Connector,
  ConnectorType,
  Scenario,
} from './types';

// ---------------------------------------------------------------------------
// Scenario A: Margaret Chen, Platinum, cruise-centric, Marriott Vacation Club
// ---------------------------------------------------------------------------

const scenarioA: Scenario = {
  id: 'a',
  shortLabel: 'A, Margaret',
  longLabel: 'Margaret Chen, Platinum, cruise centric',
  tagline:
    'Platinum cruiser, Marriott Vacation Club member. Cabin upsell, pre-cruise hotel, soft cross-sell to another timeshare brand.',
  member: {
    name: 'Margaret Chen',
    membershipNumber: 'ARR-7741-2098',
    tier: 'Platinum',
    memberSince: '2014',
    tenureYears: 12,
    lifetimeValue: '$184,200',
    homeAirport: 'RDU, Raleigh-Durham',
    pointsBalance: '42,800',
    ivrIntent: 'Wants to book a Mediterranean cruise, Sept 2026',
    initials: 'MC',
    address: {
      street: '412 Camellia Lane',
      city: 'Chapel Hill',
      state: 'NC',
      zip: '27514',
    },
    socials: [
      {
        platform: 'facebook',
        handle: '@margaret.chen.cruises',
        url: 'https://facebook.com/margaret.chen.cruises',
      },
      {
        platform: 'instagram',
        handle: '@margaretatsea',
        url: 'https://instagram.com/margaretatsea',
      },
    ],
    ownership: {
      kind: 'timeshare',
      brand: 'Marriott Vacation Club',
      since: '2016',
    },
  },
  preferences: [
    { iconKey: 'anchor', label: 'Travel style', value: 'Ocean cruising', status: 'on-file' },
    { iconKey: 'bed', label: 'Cabin preference', value: 'Premier Suite', status: 'on-file' },
    { iconKey: 'ship', label: 'Preferred cruise line', value: 'Royal Caribbean', status: 'on-file' },
    { iconKey: 'plane', label: 'Preferred airline', value: 'Delta One', status: 'on-file' },
    { iconKey: 'seat', label: 'Flight class', value: 'Business class', status: 'on-file' },
    { iconKey: 'car', label: 'Car rental', value: 'Hertz Five Star, full size', status: 'on-file' },
    { iconKey: 'shield', label: 'Travel insurance', value: 'Cruise Protect Premium, always', status: 'on-file' },
    { iconKey: 'wine', label: 'Dietary', value: 'Pescatarian', status: 'on-file' },
    { iconKey: 'passport', label: 'Passport on file', value: 'USA, expires 2029', status: 'on-file' },
  ],
  trips: [
    {
      id: 'a-t1',
      kind: 'cruise',
      title: 'Symphony of the Seas',
      details: 'Caribbean, 7 nights, Premier Suite',
      supplier: 'Royal Caribbean',
      date: 'Mar 2025',
      spend: '$14,800',
      preferred: true,
    },
    {
      id: 'a-t2',
      kind: 'flight',
      title: 'DL2218 RDU to MIA',
      details: 'Delta One, pre-cruise',
      supplier: 'Delta',
      date: 'Mar 2025',
      spend: '$1,640',
      preferred: true,
    },
    {
      id: 'a-t3',
      kind: 'hotel',
      title: 'Loews Miami Beach Hotel',
      details: '1 night pre-cruise, ocean suite',
      supplier: 'Loews',
      date: 'Mar 2025',
      spend: '$640',
      preferred: true,
    },
    {
      id: 'a-t4',
      kind: 'car',
      title: 'Hertz Five Star, Cadillac XT5',
      details: 'MIA pickup, 1 day',
      supplier: 'Hertz',
      date: 'Mar 2025',
      spend: '$160',
      preferred: true,
    },
    {
      id: 'a-t5',
      kind: 'insurance',
      title: 'Cruise Protect Premium',
      details: 'Annual, family of 2',
      supplier: 'Arrivia Insurance',
      date: 'Jan 2025',
      spend: '$540',
      preferred: true,
    },
    {
      id: 'a-t6',
      kind: 'cruise',
      title: 'Anthem of the Seas',
      details: 'Mediterranean, 10 nights, Premier Suite',
      supplier: 'Royal Caribbean',
      date: 'Sep 2024',
      spend: '$19,400',
      preferred: true,
    },
    {
      id: 'a-t7',
      kind: 'cruise',
      title: 'Ovation of the Seas',
      details: 'Alaska, 7 nights, Premier Suite',
      supplier: 'Royal Caribbean',
      date: 'Jul 2023',
      spend: '$13,600',
      preferred: true,
    },
    {
      id: 'a-t8',
      kind: 'cruise',
      title: 'Celebrity Edge',
      details: 'Caribbean, 7 nights, suite',
      supplier: 'Celebrity Cruises',
      date: 'Aug 2022',
      spend: '$9,800',
      preferred: false,
    },
  ],
  talkTrack: [
    {
      stage: 'Greeting',
      text: "Hi Margaret, thanks for holding. Welcome back, I can see you're a Platinum member with us, and you've been sailing with Royal Caribbean since 2014. I see you're looking at Mediterranean cruises for September. Are you thinking of revisiting that route, or somewhere new this time?",
      confidence: 'High confidence, based on tier and IVR intent',
      confidenceTone: 'success',
    },
    {
      stage: 'Anchor and cabin upsell',
      text: "Your last Mediterranean sailing was Anthem of the Seas in 2024, ten nights in a Premier Suite. Royal Caribbean has just launched Utopia of the Seas with the Royal Loft Suite, a private balcony and a separate living area, a step up from your Premier Suite. Would you like a comparison alongside your usual Premier?",
      confidence: 'High confidence, based on 4 prior Royal Caribbean bookings',
      confidenceTone: 'success',
      kind: 'cross-sell',
    },
    {
      stage: 'New cruise line trial',
      text: "If you'd like to try something new this trip, MSC Yacht Club sails the same Western Med route in September and the Yacht Club tier is comparable to your Premier Suite, with priority embarkation and a private restaurant. Worth a look alongside Royal Caribbean.",
      confidence: 'Medium confidence, cross-sell to new cruise line',
      confidenceTone: 'warn',
      kind: 'cross-sell',
    },
    {
      stage: 'Pre-cruise hotel night',
      text: "For Mediterranean sailings I'd strongly recommend flying into Barcelona a day early and staying overnight at the W Barcelona. That way if your flight delays you're not racing to make embarkation. I can hold a room and align it with your cruise dates in one booking.",
      confidence: 'High confidence, prior pre-cruise nights with Loews and MGM',
      confidenceTone: 'success',
      kind: 'pre-cruise',
    },
    {
      stage: 'Timeshare cross-sell',
      text: "I noticed you're with Marriott Vacation Club, you've used it twice in the Caribbean. We have a complimentary stay program with Hilton Grand Vacations in Mallorca that includes a yacht day. Members have been very happy with it, would you like me to send the details for your inbox?",
      confidence: 'Strategic, Arrivia revenue driver, brand cross-sell',
      confidenceTone: 'warn',
      kind: 'cross-sell',
    },
    {
      stage: 'Loyalty redemption',
      text: 'You currently have 42,800 Arrivia points. You can redeem them against the Royal Loft Suite upgrade, or as on-board credit for shore excursions, or against the Barcelona hotel night, your call.',
      confidence: 'High confidence, live ledger balance',
      confidenceTone: 'success',
    },
    {
      stage: 'Close',
      text: 'Shall I hold two cabin options and the Barcelona pre-cruise night while we work through the details? I can also include the Hilton Grand Vacations information in your follow-up email.',
      confidence: 'Standard close, two holds suggested',
      confidenceTone: 'muted',
    },
  ],
  talkTrackTone: 'confident',
  offersHeader: 'Recommended cruise offers',
  offersSubheader:
    "Ranked by match with Margaret's cruise history and Premier Suite preference. Cruise is Arrivia's primary revenue driver for this member.",
  offers: [
    {
      id: 'a-o1',
      title: 'Utopia of the Seas',
      ship: 'Royal Caribbean',
      itinerary: '7 nights, Western Med, Barcelona round trip',
      suite: 'Royal Loft Suite',
      price: 'from $22,400 pp',
      matchTag: 'Matches cruise line, route, suite tier',
      matchTone: 'coral',
      highlight: true,
    },
    {
      id: 'a-o2',
      title: 'MSC Seascape, Yacht Club',
      ship: 'MSC Cruises',
      itinerary: '7 nights, Western Med',
      suite: 'Yacht Club Royal Suite',
      price: 'from $19,600 pp',
      matchTag: 'New line trial, Yacht Club equivalent',
      matchTone: 'muted',
    },
    {
      id: 'a-o3',
      title: 'Wonder of the Seas',
      ship: 'Royal Caribbean',
      itinerary: '11 nights, Greek Isles',
      suite: 'Premier Suite',
      price: 'from $20,200 pp',
      matchTag: 'Longer itinerary, familiar cabin',
      matchTone: 'muted',
    },
  ],
  dataSources: [
    { id: 'crm', label: 'Arrivia CRM', status: 'connected' },
    { id: 'membership', label: 'Membership System', status: 'connected' },
    { id: 'rci', label: 'Royal Caribbean Inventory', status: 'connected' },
    { id: 'msc', label: 'MSC Inventory', status: 'connected' },
    { id: 'sabre', label: 'Sabre PNR', status: 'connected' },
    { id: 'loyalty', label: 'Arrivia Loyalty Ledger', status: 'connected' },
    { id: 'mvc', label: 'Marriott Vacation Club', status: 'connected' },
  ],
  upsell: [
    {
      id: 'a-u1',
      category: 'pre-cruise',
      title: 'Pre-cruise hotel, W Barcelona',
      pitch: "Fly in the day before so weather or a missed connection cannot cost the cruise. Margaret has done this on three prior sailings.",
      priceHint: 'from $480, 1 night',
      highlight: true,
    },
    {
      id: 'a-u2',
      category: 'upgrade',
      title: 'Cabin upgrade, Royal Loft Suite',
      pitch: 'Step up from Premier Suite, includes a separate living area and a private balcony with whirlpool. Use points to soften the price gap.',
      priceHint: '+$3,500 vs Premier Suite, or 28,000 points',
    },
    {
      id: 'a-u3',
      category: 'flight',
      title: 'Delta One, RDU to BCN via JFK',
      pitch: 'Lie-flat seat, aligns with her preferred class. Open jaw via Rome on the return if she wants a few days post-cruise.',
      priceHint: 'from $4,800 pp round trip',
    },
    {
      id: 'a-u4',
      category: 'insurance',
      title: 'Cruise Protect Premium, top up',
      pitch: 'Margaret renews this annually. Trip cost exceeds her current cover, top up to the higher band before close.',
      priceHint: '$120 top up for trip value over $25,000',
    },
    {
      id: 'a-u5',
      category: 'car',
      title: 'Hertz Five Star pickup in Barcelona',
      pitch: 'For the pre-cruise night and a half day exploring Montserrat. Aligns with her existing Hertz status.',
      priceHint: 'from $90, 24 hours',
    },
  ],
  upsellHeader: 'Suggested add-ons for this trip',
  // No platinum pitch, she is already Platinum
};

// ---------------------------------------------------------------------------
// Scenario B: David Okafor, Silver, sparse profile, degraded connectors
// Wyndham Destinations member, cross-sell to a different timeshare brand
// ---------------------------------------------------------------------------

const scenarioB: Scenario = {
  id: 'b',
  shortLabel: 'B, David',
  longLabel: 'David Okafor, Silver, sparse profile',
  tagline:
    'Silver Wyndham member with one trip on file. Capture missing data, soft cross-sell to a different timeshare brand, two feeds degraded.',
  member: {
    name: 'David Okafor',
    membershipNumber: 'ARR-4419-0033',
    tier: 'Silver',
    memberSince: '2024',
    tenureYears: 2,
    lifetimeValue: '$1,800',
    homeAirport: 'Not on file',
    homeAirportStatus: 'not-on-file',
    pointsBalance: '1,250',
    ivrIntent: 'Caller did not state intent, please discover',
    ivrIntentMissing: true,
    initials: 'DO',
    address: {
      street: '1809 Tryon Hills Drive',
      city: 'Charlotte',
      state: 'NC',
      zip: '28206',
    },
    socials: [
      {
        platform: 'facebook',
        handle: '@david.okafor.0033',
        url: 'https://facebook.com/david.okafor.0033',
      },
    ],
    ownership: {
      kind: 'timeshare',
      brand: 'Wyndham Destinations',
      since: '2023',
    },
  },
  preferences: [
    {
      iconKey: 'anchor',
      label: 'Travel style',
      value: 'Cruise, inferred from 1 trip',
      status: 'inferred',
    },
    { iconKey: 'bed', label: 'Cabin preference', value: 'Not on file', status: 'not-on-file' },
    {
      iconKey: 'ship',
      label: 'Preferred cruise line',
      value: 'Norwegian, inferred',
      status: 'inferred',
    },
    {
      iconKey: 'plane',
      label: 'Preferred airline',
      value: 'Not currently available',
      status: 'feed-unavailable',
    },
    { iconKey: 'seat', label: 'Flight class', value: 'Not on file', status: 'not-on-file' },
    {
      iconKey: 'car',
      label: 'Car rental',
      value: 'Not currently available',
      status: 'feed-unavailable',
    },
    { iconKey: 'shield', label: 'Travel insurance', value: 'Not on file', status: 'not-on-file' },
    { iconKey: 'wine', label: 'Dietary', value: 'Not on file', status: 'not-on-file' },
    { iconKey: 'passport', label: 'Passport on file', value: 'Not on file', status: 'not-on-file' },
  ],
  trips: [
    {
      id: 'b-t1',
      kind: 'cruise',
      title: 'Norwegian Encore',
      details: 'Caribbean, 7 nights, Inside cabin',
      supplier: 'Norwegian Cruise Line',
      date: 'Oct 2024',
      spend: '$1,800',
      preferred: false,
    },
  ],
  talkTrack: [
    {
      stage: 'Greeting and open question',
      text: "Hi David, thanks for waiting. I can see you joined Arrivia last year and you took a 7 night Caribbean with Norwegian, hope that went well. What can I help you with today?",
      confidence: 'Open, no stated intent yet',
      confidenceTone: 'muted',
    },
    {
      stage: 'Discover intent',
      text: 'Before we dive in, can I ask a couple of quick questions to make sure I show you the right options? Are you thinking another cruise, or air and a hotel package this time? Solo, couple, or family?',
      confidence: 'Discovery, limited history',
      confidenceTone: 'muted',
    },
    {
      stage: 'Capture missing data, gently',
      text: "Whatever we book, I want to make sure your details are right. I can see we don't have your passport, dietary preferences, home airport, or travel insurance preference on file yet. Could we capture those while we chat, it will save us five minutes later and unlocks better pricing on insurance bundles.",
      confidence: 'High value, 4 not-on-file fields to capture',
      confidenceTone: 'success',
      kind: 'capture-data',
    },
    {
      stage: 'Connector caveat',
      text: 'Quick note for me, our Norwegian inventory feed and our preferred airline feed are unavailable right now. I can quote Royal Caribbean and Carnival live, and I will email Norwegian options inside 30 minutes once that feed comes back. Want me to move forward with the live options and follow up on Norwegian?',
      confidence: 'Norwegian and airline feed offline, transparent caveat',
      confidenceTone: 'warn',
    },
    {
      stage: 'Timeshare cross-sell',
      text: "I see you're with Wyndham Destinations, and we have a try-before-you-buy program with Disney Vacation Club at Aulani in Hawaii. A two night stay, no obligation. It's been popular with Wyndham members looking to compare. Would you like me to send the brochure?",
      confidence: 'Strategic, Arrivia revenue driver, brand cross-sell',
      confidenceTone: 'warn',
      kind: 'cross-sell',
    },
    {
      stage: 'Loyalty tie-in',
      text: "You're on Silver with 1,250 Arrivia points. The ledger is mid-sync so the balance may move a touch by close of call. Today's booking will get you closer to Gold, and I can show you what that unlocks if useful.",
      confidence: 'Live ledger sync pending, balance may be stale',
      confidenceTone: 'warn',
    },
    {
      stage: 'Close',
      text: 'Want me to capture the missing details first, then walk through two cruise options on the lines that are live? I will email Norwegian alternatives when the feed is back.',
      confidence: 'Soft close, data capture first',
      confidenceTone: 'muted',
    },
  ],
  talkTrackTone: 'discovery',
  offersHeader: 'Starter options',
  offersSubheader:
    'Limited confidence. Built from one prior booking, several preferences not on file, and one supplier offline. Treat as starter ideas.',
  offers: [
    {
      id: 'b-o1',
      title: 'Norwegian Encore',
      ship: 'Norwegian Cruise Line',
      itinerary: '7 nights, Caribbean',
      suite: 'Inside cabin',
      price: 'pricing unavailable',
      matchTag: 'Matches last booking, inventory feed offline',
      matchTone: 'warn',
      unavailable: true,
    },
    {
      id: 'b-o2',
      title: 'Symphony of the Seas',
      ship: 'Royal Caribbean',
      itinerary: '7 nights, Caribbean',
      suite: 'Ocean view cabin',
      price: 'from $1,950 pp',
      matchTag: 'New line, similar itinerary, live pricing',
      matchTone: 'muted',
    },
    {
      id: 'b-o3',
      title: 'Carnival Mardi Gras',
      ship: 'Carnival Cruise Line',
      itinerary: '7 nights, Caribbean',
      suite: 'Balcony cabin',
      price: 'from $2,400 pp',
      matchTag: 'Step up from prior cabin tier',
      matchTone: 'muted',
    },
  ],
  dataSources: [
    {
      id: 'crm',
      label: 'Arrivia CRM',
      status: 'pending',
      detail: 'Partial sync, last 4 hours ago',
    },
    { id: 'membership', label: 'Membership System', status: 'connected' },
    {
      id: 'ncl',
      label: 'Norwegian Inventory',
      status: 'error',
      detail: 'Feed unavailable',
    },
    { id: 'rci', label: 'Royal Caribbean Inventory', status: 'connected' },
    {
      id: 'airpref',
      label: 'Preferred Airline Feed',
      status: 'error',
      detail: 'Endpoint timing out',
    },
    {
      id: 'loyalty',
      label: 'Arrivia Loyalty Ledger',
      status: 'pending',
      detail: 'Sync pending, 47 min ago',
    },
    { id: 'wyndham', label: 'Wyndham Destinations', status: 'connected' },
  ],
  alerts: [
    {
      level: 'warn',
      title: 'Two feeds are unavailable for this caller',
      detail:
        'Norwegian Cruise Line inventory and the preferred airline feed are offline. These are temporary outages, distinct from missing profile data below. The talk track adapts.',
    },
    {
      level: 'info',
      title: 'Profile is sparse, 5 fields not on file',
      detail:
        'Passport, dietary, home airport, flight class, travel insurance, all empty. The talk track includes a gentle capture prompt while the caller is engaged.',
    },
  ],
  upsell: [
    {
      id: 'b-u1',
      category: 'flight',
      title: 'Air package, Charlotte to Caribbean',
      pitch: "We don't have a preferred airline on file yet. Capture that during the call so you can quote one-stop and non-stop options from CLT immediately.",
      priceHint: 'Capture preference first',
      highlight: true,
    },
    {
      id: 'b-u2',
      category: 'accommodation',
      title: 'Pre-cruise hotel, port night in Miami',
      pitch: 'A safety net for a Caribbean sailing. David flew the same day last trip, so this is a real change in service.',
      priceHint: 'from $180, 1 night',
    },
    {
      id: 'b-u3',
      category: 'car',
      title: 'Port transfer or Hertz pickup',
      pitch: 'Capture the car rental preference during this call. Default to a transfer if he prefers not to drive.',
      priceHint: 'transfer from $45, Hertz from $60',
    },
    {
      id: 'b-u4',
      category: 'insurance',
      title: 'Travel insurance, basic cruise cover',
      pitch: "We don't have insurance on file. With a 7 night Caribbean trip and weather risk, this is an easy add and shows we are looking after him.",
      priceHint: 'from $89, basic cover',
    },
    {
      id: 'b-u5',
      category: 'upgrade',
      title: 'Cabin upgrade, Inside to Ocean view',
      pitch: 'Modest step up from his last booking, frames the upsell as a comfort improvement rather than a luxury splurge.',
      priceHint: '+$240 pp on Royal Caribbean',
    },
  ],
  upsellHeader: 'Suggested add-ons and capture moments',
  platinumPitch: {
    headline: 'David is on Silver, two tiers from Platinum',
    bullets: [
      'Platinum opens every cruise line in the Arrivia catalogue, including the ones we cannot offer Silver members today.',
      'All-resort access, including the timeshare partners across Marriott, Hilton, Disney, Hyatt, and Wyndham, with member rate parity.',
      'Free standard travel insurance on bookings over $5,000, which David almost certainly does not have on file.',
      'Priority cabin booking and 48-hour holds without deposit on cruises.',
    ],
    example:
      "If David books the Royal Caribbean Symphony with cabin upgrade and pre-cruise hotel, he is one cruise away from Gold, two away from Platinum. Frame Platinum as a near-term goal, not a vague aspiration.",
    ctaLine:
      'David, I can see today\'s booking will get you most of the way to Gold. If you book one more cruise inside 18 months, you hit Platinum, which opens every cruise line and timeshare resort we work with. Want me to flag a callback at the right moment to look at Platinum?',
  },
};

// ---------------------------------------------------------------------------
// Scenario C: Sarah Mitchell, Gold, American Express Business Travel
// Vegas trip, multi-product, not a timeshare owner
// ---------------------------------------------------------------------------

const scenarioC: Scenario = {
  id: 'c',
  shortLabel: 'C, Sarah',
  longLabel: 'Sarah Mitchell, Gold, American Express Business Travel',
  tagline:
    'Gold AmEx Business Travel member, not a timeshare owner. Vegas trip, multi-product. Strong Platinum upgrade candidate.',
  member: {
    name: 'Sarah Mitchell',
    membershipNumber: 'ARR-9214-6650',
    tier: 'Gold',
    memberSince: '2019',
    tenureYears: 7,
    lifetimeValue: '$58,400',
    homeAirport: 'CLT, Charlotte',
    pointsBalance: '18,500',
    ivrIntent: 'Wants to book a Las Vegas trip, family, late July',
    initials: 'SM',
    address: {
      street: '227 Glenwood Ave, Apt 4B',
      city: 'Raleigh',
      state: 'NC',
      zip: '27603',
    },
    socials: [
      {
        platform: 'facebook',
        handle: '@sarah.mitchell.raleigh',
        url: 'https://facebook.com/sarah.mitchell.raleigh',
      },
      {
        platform: 'linkedin',
        handle: '@sarahmitchell-cmo',
        url: 'https://linkedin.com/in/sarahmitchell-cmo',
      },
    ],
    ownership: {
      kind: 'business',
      partner: 'American Express',
      programLabel: 'AmEx Business Travel, Platinum Card',
    },
  },
  preferences: [
    { iconKey: 'anchor', label: 'Travel style', value: 'City breaks and business', status: 'on-file' },
    { iconKey: 'bed', label: 'Hotel preference', value: 'Bellagio or Wynn, Strip view', status: 'on-file' },
    { iconKey: 'plane', label: 'Preferred airline', value: 'American Airlines', status: 'on-file' },
    { iconKey: 'seat', label: 'Flight class', value: 'First class on AA', status: 'on-file' },
    { iconKey: 'car', label: 'Car rental', value: 'Hertz Gold, full size', status: 'on-file' },
    { iconKey: 'shield', label: 'Travel insurance', value: 'AmEx Platinum cover, plus top-up', status: 'on-file' },
    { iconKey: 'wine', label: 'Dietary', value: 'No restrictions', status: 'on-file' },
    { iconKey: 'passport', label: 'Passport on file', value: 'USA, expires 2031', status: 'on-file' },
  ],
  trips: [
    {
      id: 'c-t1',
      kind: 'hotel',
      title: 'Bellagio, Lakeview suite',
      details: 'Las Vegas, 3 nights, business conference',
      supplier: 'MGM Resorts',
      date: 'Feb 2025',
      spend: '$2,140',
      preferred: true,
    },
    {
      id: 'c-t2',
      kind: 'flight',
      title: 'AA1402 CLT to LAS',
      details: 'First class, round trip',
      supplier: 'American Airlines',
      date: 'Feb 2025',
      spend: '$1,840',
      preferred: true,
    },
    {
      id: 'c-t3',
      kind: 'car',
      title: 'Hertz Gold, Mercedes E-Class',
      details: 'LAS pickup, 3 days',
      supplier: 'Hertz',
      date: 'Feb 2025',
      spend: '$420',
      preferred: true,
    },
    {
      id: 'c-t4',
      kind: 'insurance',
      title: 'Business Travel top-up',
      details: 'Top-up over AmEx Platinum cover',
      supplier: 'Arrivia Insurance',
      date: 'Feb 2025',
      spend: '$95',
      preferred: true,
    },
    {
      id: 'c-t5',
      kind: 'hotel',
      title: 'Hyatt Regency Atlanta',
      details: '2 nights, conference',
      supplier: 'Hyatt',
      date: 'Nov 2024',
      spend: '$840',
      preferred: true,
    },
    {
      id: 'c-t6',
      kind: 'flight',
      title: 'AA862 CLT to ATL',
      details: 'First class',
      supplier: 'American Airlines',
      date: 'Nov 2024',
      spend: '$520',
      preferred: true,
    },
    {
      id: 'c-t7',
      kind: 'hotel',
      title: 'Wynn Las Vegas',
      details: '4 nights, leisure with family',
      supplier: 'Wynn Resorts',
      date: 'Jul 2024',
      spend: '$3,200',
      preferred: true,
    },
    {
      id: 'c-t8',
      kind: 'car',
      title: 'Hertz Gold, Cadillac Escalade',
      details: 'LAS pickup, 4 days',
      supplier: 'Hertz',
      date: 'Jul 2024',
      spend: '$680',
      preferred: true,
    },
  ],
  talkTrack: [
    {
      stage: 'Greeting and AmEx recognition',
      text: "Hi Sarah, thanks for holding. I can see you're a Gold member with us and you book through your AmEx Business Travel program, welcome back. The IVR has you down for a Las Vegas family trip in late July, is that for the four of you again?",
      confidence: 'High confidence, based on AmEx record and IVR intent',
      confidenceTone: 'success',
    },
    {
      stage: 'Hotel, the headline product',
      text: "You've stayed at Bellagio for business and Wynn with the family. For a July family trip with the pool weather, Bellagio Lakeview suites are stronger for kids than Wynn, and the new Fountains View rooms have been popular this season. Want me to price Bellagio first, then compare with Wynn?",
      confidence: 'High confidence, based on 2 prior Vegas stays',
      confidenceTone: 'success',
    },
    {
      stage: 'Flights from Charlotte',
      text: 'American non-stop CLT to LAS in First, the way you booked in February. July fares are still soft, I can lock in same-day departure and a red-eye return so you do not lose a day on either end.',
      confidence: 'High confidence, based on 2 prior AA bookings',
      confidenceTone: 'success',
    },
    {
      stage: 'Car rental',
      text: "Hertz Gold pickup at LAS, same as last time. The Escalade was a good fit for the family, want me to put that on hold? I can also bundle a 24 hour Strip valet credit since you'll be at the casinos.",
      confidence: 'High confidence, Hertz Gold on file',
      confidenceTone: 'success',
    },
    {
      stage: 'Travel insurance',
      text: 'Your AmEx Platinum cover handles most of this, but trip value lands above the cap once we add four flights and four nights at Bellagio. I would recommend a top-up policy, $95 last time, similar this time.',
      confidence: 'High confidence, top-up pattern on file',
      confidenceTone: 'success',
    },
    {
      stage: 'Platinum upgrade pitch',
      text: "Quick one, you are one cruise or two more bookings of this size from Platinum. Platinum unlocks every cruise line in our catalogue and waives travel insurance on bookings over $5,000, which would cover both your Bellagio and Wynn trips. Worth a 30 second look at the benefits before we close?",
      confidence: 'Strategic, AmEx Business Travel volume justifies pitch',
      confidenceTone: 'warn',
      kind: 'platinum',
    },
    {
      stage: 'Close',
      text: 'Shall I hold Bellagio Lakeview, the AA non-stop, the Escalade pickup, and price the insurance top-up? I will also email you the Platinum benefits sheet to read at your leisure.',
      confidence: 'Multi-product hold, standard close',
      confidenceTone: 'muted',
    },
  ],
  talkTrackTone: 'confident',
  offersHeader: 'Recommended Vegas package',
  offersSubheader:
    "Built around Sarah's confirmed preferences, four travellers in late July, multi-product trip.",
  offers: [
    {
      id: 'c-o1',
      title: 'Bellagio Lakeview Suite',
      ship: 'MGM Resorts',
      itinerary: '4 nights, late July, family of 4',
      suite: 'Lakeview Suite, Strip view',
      price: 'from $549 per night',
      matchTag: 'Matches: prior stay, family configuration',
      matchTone: 'coral',
      highlight: true,
      kind: 'hotel',
    },
    {
      id: 'c-o2',
      title: 'Wynn Las Vegas Tower Suite',
      ship: 'Wynn Resorts',
      itinerary: '4 nights, late July, Strip view',
      suite: 'Tower Suite Salon',
      price: 'from $620 per night',
      matchTag: 'Familiar property, premium pool club',
      matchTone: 'muted',
      kind: 'hotel',
    },
    {
      id: 'c-o3',
      title: 'Fontainebleau Las Vegas',
      ship: 'Fontainebleau',
      itinerary: '4 nights, late July, Strip view',
      suite: 'Hibiscus Suite',
      price: 'from $480 per night',
      matchTag: 'New property trial, AmEx Fine Hotels',
      matchTone: 'muted',
      kind: 'hotel',
    },
  ],
  dataSources: [
    { id: 'crm', label: 'Arrivia CRM', status: 'connected' },
    { id: 'membership', label: 'Membership System', status: 'connected' },
    { id: 'amex-bt', label: 'AmEx Business Travel', status: 'connected' },
    { id: 'mgm', label: 'MGM Resorts Inventory', status: 'connected' },
    { id: 'wynn', label: 'Wynn Resorts Inventory', status: 'connected' },
    { id: 'aa', label: 'American Airlines NDC', status: 'connected' },
    { id: 'hertz', label: 'Hertz Inventory', status: 'connected' },
    { id: 'loyalty', label: 'Arrivia Loyalty Ledger', status: 'connected' },
  ],
  upsell: [
    {
      id: 'c-u1',
      category: 'accommodation',
      title: 'Bellagio Lakeview Suite, family configuration',
      pitch: 'Headline product. Same property she booked in February, larger room for four. Price the Fountains View room as a soft upgrade.',
      priceHint: 'from $549 per night',
      highlight: true,
    },
    {
      id: 'c-u2',
      category: 'flight',
      title: 'American Airlines First, CLT to LAS',
      pitch: 'Direct flight, four First class seats. Bundle for a meaningful discount over four individual tickets.',
      priceHint: 'from $1,840 pp round trip',
    },
    {
      id: 'c-u3',
      category: 'car',
      title: 'Hertz Gold, Cadillac Escalade',
      pitch: "Sarah's go-to in Vegas. Add the Strip valet credit, $40 in product cost, $80 in perceived value.",
      priceHint: 'from $189 per day',
    },
    {
      id: 'c-u4',
      category: 'insurance',
      title: 'Travel insurance top-up over AmEx Platinum',
      pitch: 'AmEx Platinum covers most of the trip, but four travellers at this trip value exceeds the cap. Confirm cover, attach the top-up.',
      priceHint: '$95 to $150 depending on trip value',
    },
    {
      id: 'c-u5',
      category: 'upgrade',
      title: 'Show, dining, and pool club bundle',
      pitch: 'Cirque du Soleil pre-booking, two restaurant reservations, Encore Beach Club day pass. Pure margin for Arrivia, high perceived value.',
      priceHint: '$320 to $620 depending on options',
    },
  ],
  upsellHeader: 'Vegas package add-ons',
  platinumPitch: {
    headline: 'Sarah is on Gold, one tier from Platinum',
    bullets: [
      'Platinum opens every cruise line in the Arrivia catalogue, including the partner timeshare resorts.',
      'Free standard travel insurance on every booking over $5,000, this Vegas trip would have qualified.',
      'AmEx Business Travel members on Platinum get cross-program rate parity with the timeshare network.',
      'Priority hotel suite upgrades and complimentary fourth night on stays of 4 or more.',
    ],
    example:
      "Sarah's Vegas trip alone will push lifetime value past $60,000, the band where retention math favours pushing for Platinum. Best moment to pitch is after the hold, when the trip feels real but the booking is reversible.",
    ctaLine:
      "Sarah, on this Vegas trip alone you'll cross the threshold for Platinum. Platinum opens every cruise line we work with, gives you free insurance on bookings over $5,000, and matches your AmEx Business Travel benefits across our timeshare partners. Worth a 30 second look at the benefits sheet before we close?",
  },
};

// ---------------------------------------------------------------------------
// Scenario registry
// ---------------------------------------------------------------------------

export const scenarios: Record<string, Scenario> = {
  a: scenarioA,
  b: scenarioB,
  c: scenarioC,
};

export const scenarioList: Scenario[] = [scenarioA, scenarioB, scenarioC];

export function getScenario(id?: string | null): Scenario {
  if (id && scenarios[id]) return scenarios[id];
  return scenarioA;
}

// ---------------------------------------------------------------------------
// Connector catalogue, page 2 data, lightly scenario-aware
// ---------------------------------------------------------------------------

const palette = [
  'bg-arrivia-blue-600 text-white',
  'bg-arrivia-coral-500 text-white',
  'bg-arrivia-slate-700 text-white',
  'bg-arrivia-blue-400 text-white',
  'bg-arrivia-coral-300 text-arrivia-slate-900',
  'bg-arrivia-slate-500 text-white',
];

function pickAccent(i: number) {
  return palette[i % palette.length];
}

const baseConnectors: Connector[] = [
  {
    id: 'crm',
    name: 'Arrivia CRM',
    type: 'Internal',
    status: 'connected',
    lastSync: '2 min ago',
    initials: 'AC',
    accent: pickAccent(0),
    authType: 'MCP Server URL',
    description: 'Primary CRM with member, trip, and preference data.',
    mcpTools: [
      'crm.getMember(membershipNumber)',
      'crm.getTripHistory(memberId)',
      'crm.getPreferences(memberId)',
      'crm.updatePreference(memberId, key, value)',
      'crm.createBooking(memberId, payload)',
      'crm.getLoyaltyBalance(memberId)',
    ],
  },
  {
    id: 'membership',
    name: 'Arrivia Membership System',
    type: 'Internal',
    status: 'connected',
    lastSync: '5 min ago',
    initials: 'AM',
    accent: pickAccent(1),
    authType: 'API Key',
    description: 'Tier, status, and benefits engine.',
  },
  {
    id: 'loyalty',
    name: 'Arrivia Loyalty Ledger',
    type: 'Internal',
    status: 'connected',
    lastSync: '1 min ago',
    initials: 'LL',
    accent: pickAccent(2),
    authType: 'API Key',
    description: 'Points balance, accrual, and redemption ledger.',
  },
  {
    id: 'rci',
    name: 'Royal Caribbean Inventory API',
    type: 'Supplier',
    status: 'connected',
    lastSync: '3 min ago',
    initials: 'RC',
    accent: pickAccent(3),
    authType: 'OAuth 2.0',
  },
  {
    id: 'carnival',
    name: 'Carnival Cruise Line API',
    type: 'Supplier',
    status: 'connected',
    lastSync: '12 min ago',
    initials: 'CC',
    accent: pickAccent(4),
    authType: 'OAuth 2.0',
  },
  {
    id: 'ncl',
    name: 'Norwegian Cruise Line',
    type: 'Supplier',
    status: 'disconnected',
    lastSync: '4 days ago',
    initials: 'NC',
    accent: pickAccent(5),
    authType: 'OAuth 2.0',
  },
  {
    id: 'msc',
    name: 'MSC Cruises',
    type: 'Supplier',
    status: 'connected',
    lastSync: '7 min ago',
    initials: 'MS',
    accent: pickAccent(0),
    authType: 'OAuth 2.0',
  },
  {
    id: 'aa',
    name: 'American Airlines NDC',
    type: 'Air',
    status: 'connected',
    lastSync: '4 min ago',
    initials: 'AA',
    accent: pickAccent(1),
    authType: 'OAuth 2.0',
  },
  {
    id: 'delta',
    name: 'Delta NDC',
    type: 'Air',
    status: 'connected',
    lastSync: '5 min ago',
    initials: 'DL',
    accent: pickAccent(2),
    authType: 'OAuth 2.0',
  },
  {
    id: 'sabre',
    name: 'Sabre GDS',
    type: 'Air',
    status: 'connected',
    lastSync: '2 min ago',
    initials: 'SG',
    accent: pickAccent(3),
    authType: 'Basic',
  },
  {
    id: 'amadeus',
    name: 'Amadeus GDS',
    type: 'Air',
    status: 'error',
    errorMessage: 'Credentials expired',
    lastSync: '2 days ago',
    initials: 'AG',
    accent: pickAccent(4),
    authType: 'Basic',
  },
  {
    id: 'mgm',
    name: 'MGM Resorts Inventory',
    type: 'Hotel',
    status: 'connected',
    lastSync: '11 min ago',
    initials: 'MG',
    accent: pickAccent(5),
    authType: 'OAuth 2.0',
  },
  {
    id: 'wynn',
    name: 'Wynn Resorts Inventory',
    type: 'Hotel',
    status: 'connected',
    lastSync: '13 min ago',
    initials: 'WR',
    accent: pickAccent(0),
    authType: 'OAuth 2.0',
  },
  {
    id: 'expedia',
    name: 'Expedia TAAP',
    type: 'Hotel',
    status: 'connected',
    lastSync: '15 min ago',
    initials: 'ET',
    accent: pickAccent(1),
    authType: 'API Key',
  },
  {
    id: 'hertz',
    name: 'Hertz Inventory',
    type: 'Activities',
    status: 'connected',
    lastSync: '9 min ago',
    initials: 'HZ',
    accent: pickAccent(2),
    authType: 'API Key',
  },
  {
    id: 'mvc',
    name: 'Marriott Vacation Club',
    type: 'Supplier',
    status: 'connected',
    lastSync: '8 min ago',
    initials: 'MV',
    accent: pickAccent(3),
    authType: 'OAuth 2.0',
  },
  {
    id: 'wyndham',
    name: 'Wyndham Destinations',
    type: 'Supplier',
    status: 'connected',
    lastSync: '14 min ago',
    initials: 'WD',
    accent: pickAccent(4),
    authType: 'OAuth 2.0',
  },
  {
    id: 'hgv',
    name: 'Hilton Grand Vacations',
    type: 'Supplier',
    status: 'connected',
    lastSync: '10 min ago',
    initials: 'HG',
    accent: pickAccent(5),
    authType: 'OAuth 2.0',
  },
  {
    id: 'dvc',
    name: 'Disney Vacation Club',
    type: 'Supplier',
    status: 'connected',
    lastSync: '6 min ago',
    initials: 'DV',
    accent: pickAccent(0),
    authType: 'OAuth 2.0',
  },
  {
    id: 'amex-bt',
    name: 'AmEx Business Travel',
    type: 'CRM',
    status: 'connected',
    lastSync: '3 min ago',
    initials: 'AX',
    accent: pickAccent(1),
    authType: 'OAuth 2.0',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    type: 'Payments',
    status: 'connected',
    lastSync: '4 min ago',
    initials: 'St',
    accent: pickAccent(2),
    authType: 'API Key',
  },
  {
    id: 'twilio',
    name: 'Twilio Voice',
    type: 'Telephony',
    status: 'connected',
    lastSync: 'just now',
    initials: 'Tw',
    accent: pickAccent(3),
    authType: 'API Key',
  },
  {
    id: 'claude',
    name: 'Anthropic Claude (Symphony AI)',
    type: 'AI',
    status: 'connected',
    lastSync: '1 min ago',
    initials: 'AI',
    accent: pickAccent(4),
    authType: 'API Key',
  },
  {
    id: 'salesforce',
    name: 'Salesforce Service Cloud',
    type: 'CRM',
    status: 'connected',
    lastSync: '7 min ago',
    initials: 'SF',
    accent: pickAccent(5),
    authType: 'OAuth 2.0',
  },
];

// Scenario B overrides on the connectors page, reflecting the same degraded
// state the agent screen reflects.
const scenarioBConnectorOverrides: Record<string, Partial<Connector>> = {
  crm: { status: 'pending', lastSync: '4 hours ago' },
  loyalty: { status: 'pending', lastSync: '47 min ago' },
  delta: { status: 'error', errorMessage: 'Endpoint timing out', lastSync: '23 min ago' },
};

export function getConnectors(scenarioId: string): Connector[] {
  if (scenarioId !== 'b') return baseConnectors;
  return baseConnectors.map((c) =>
    scenarioBConnectorOverrides[c.id]
      ? { ...c, ...scenarioBConnectorOverrides[c.id] }
      : c
  );
}

// Re-exported for backwards compatibility, defaults to scenario A view.
export const connectors = baseConnectors;

export interface CatalogueItem {
  id: string;
  name: string;
  type: ConnectorType;
  category: string;
  initials: string;
  accent: string;
  recommended?: boolean;
  authType: AuthType;
  description: string;
}

export const catalogue: CatalogueItem[] = [
  {
    id: 'arrivia-crm-mcp',
    name: 'Arrivia CRM (MCP)',
    type: 'Internal',
    category: 'Internal',
    initials: 'AC',
    accent: 'bg-arrivia-coral-500 text-white',
    recommended: true,
    authType: 'MCP Server URL',
    description:
      'Recommended. Exposes member, trip, preference, and loyalty tools via the Arrivia MCP server. Best path for agentic flows.',
  },
  {
    id: 'princess',
    name: 'Princess Cruises',
    type: 'Supplier',
    category: 'Supplier, Cruise',
    initials: 'PC',
    accent: 'bg-arrivia-blue-500 text-white',
    authType: 'OAuth 2.0',
    description: 'Inventory and pricing for Princess Cruises sailings worldwide.',
  },
  {
    id: 'holland',
    name: 'Holland America',
    type: 'Supplier',
    category: 'Supplier, Cruise',
    initials: 'HA',
    accent: 'bg-arrivia-blue-400 text-white',
    authType: 'OAuth 2.0',
    description: 'Inventory and pricing for Holland America Line.',
  },
  {
    id: 'hyatt-vc',
    name: 'Hyatt Vacation Club',
    type: 'Supplier',
    category: 'Supplier, Timeshare',
    initials: 'HV',
    accent: 'bg-arrivia-slate-700 text-white',
    authType: 'OAuth 2.0',
    description: 'Timeshare inventory across Hyatt Vacation Club destinations.',
  },
  {
    id: 'qantas',
    name: 'Qantas',
    type: 'Air',
    category: 'Air',
    initials: 'QF',
    accent: 'bg-arrivia-coral-600 text-white',
    authType: 'API Key',
    description: 'Direct NDC connection to Qantas, including frequent flyer fares.',
  },
  {
    id: 'singapore-airlines',
    name: 'Singapore Airlines',
    type: 'Air',
    category: 'Air',
    initials: 'SQ',
    accent: 'bg-arrivia-blue-600 text-white',
    authType: 'API Key',
    description: 'Inventory and KrisFlyer redemption availability.',
  },
  {
    id: 'marriott-bonvoy',
    name: 'Marriott Bonvoy',
    type: 'Hotel',
    category: 'Hotel',
    initials: 'MB',
    accent: 'bg-arrivia-slate-500 text-white',
    authType: 'OAuth 2.0',
    description: 'Hotel inventory, Bonvoy points pricing, and member status pass-through.',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    type: 'CRM',
    category: 'CRM',
    initials: 'HS',
    accent: 'bg-arrivia-coral-500 text-white',
    authType: 'OAuth 2.0',
    description: 'Sync agent activity, callbacks, and follow-ups into HubSpot.',
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    type: 'CRM',
    category: 'CRM',
    initials: 'ZD',
    accent: 'bg-arrivia-slate-700 text-white',
    authType: 'OAuth 2.0',
    description: 'Bring service tickets and case history into the agent console.',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'AI',
    category: 'AI',
    initials: 'OA',
    accent: 'bg-arrivia-slate-900 text-white',
    authType: 'API Key',
    description: 'Alternative model provider for Symphony AI components.',
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    type: 'AI',
    category: 'AI',
    initials: 'PN',
    accent: 'bg-arrivia-blue-500 text-white',
    authType: 'API Key',
    description: 'Vector database for retrieval over Arrivia knowledge base.',
  },
];
